/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ergh;

import java.util.Random;

public class Library {
		
		public static void main(String[] args) {
			Random random = new Random();
			
			int a = 0; 
			int b = random.nextInt(10);
			
			System.out.println("Список рандомных чисел, рандомного кол-ва!:)");
			
			for (int i = 0; i <= b; i++) {
				
				if(i < b) {
				a = random.nextInt(50);
				System.out.print(a + ", ");
				}else {
					System.out.println(a + ".");
				}
			}
    }
}
