INSERT INTO author(id, first_name, last_name, date_of_birth)VALUES (1, 'Jane', 'Austen', '1775-12-16');
INSERT INTO author(id, first_name, last_name, date_of_birth)VALUES (2, 'Alexandre', 'Dumas', '1802-07-24');
INSERT INTO author(id, first_name, last_name, date_of_birth)VALUES (3, 'Joanne', 'Rowling', '1965-07-31');
INSERT INTO author(id, first_name, last_name, date_of_birth)VALUES (4, 'Stephen', 'King', '1947-09-21');
INSERT INTO language(id, name)VALUES (1, 'RU');
INSERT INTO language(id, name)VALUES (2, 'EN');
INSERT INTO language(id, name)VALUES (3, 'FR');
INSERT INTO book(id, author_id, language_id, name, published_in)VALUES (1, 1, 1, 'Sense and Sensibility', 1811);
INSERT INTO book(id, author_id, language_id, name, published_in)VALUES (2, 1, 2, 'Pride and Prejudice', 1813);
INSERT INTO book(id, author_id, language_id, name, published_in)VALUES (3, 2, 2, 'Le Capitaine Paul', 1838);
INSERT INTO book(id, author_id, language_id, name, published_in)VALUES (4, 2, 1, 'Le Capitaine Pamphile', 1839);
INSERT INTO book(id, author_id, language_id, name, published_in)VALUES (5, 1, 3, 'Northanger Abbey', 1818);
