/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sp.courses;

public class Library {
    public static void main(String[] args) {
    	System.out.println("Hello world!!!");
    }
}
